language: php

matrix:
  include:
    - php: 7.3
      env:
        - SYMFONY_VERSION='5.0.*'
    - php: 7.4
      env:
        - SYMFONY_VERSION='5.0.*'
    - php: 8.0
      env:
        - SYMFONY_VERSION='5.0.*'

before_install:
    - mkdir -p build/logs
    - composer self-update
    - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi;'

install:
    - composer require php-coveralls/php-coveralls '~1.0'

after_success:
    - php vendor/bin/coveralls
